[package]
name = "moni"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "controller"
path = "src/controllers/index.rs"

[dependencies]
rocket = "0.5.0-rc.3"
serde = "1.0.162"
serde_json = "1.0.96"
